
ffcmdprefix = 'ffmpeg -benchmark -y -loglevel verbose'
framerate = 24.0

[inputs_defaults]
thread_queue_size = 512

[inputs]
# -video_size 1920x1080 -framerate 25 -thread_queue_size 512  -f avfoundation -i 3:none \
[inputs.mac.v]
f = 'avfoundation'
i = '%d:none'
[inputs.mac.a]
f = 'avfoundation'
i = 'none:%d'


#  -map 1:v -c:v vp9 -s 1920x1080 -framerate 25  -benchmark -speed 5 -tile-columns 6 -frame-parallel 1 -threads 8 -static-thresh 0 -max-intra-rate 300 -deadline realtime  -crf 9 -lag-in-frames 9 -row-mt 1 -error-resilient 1

[presets]

[presets.opus-default]
fileext = 'opus'
type = 'a'
codec = 'libopus'

[presets.vp9-default]
fileext = "webm"
type = "v"
codec = "vp9"

[presets.opus-voice]
fileext = 'opus'
type = 'a'
codec = 'libopus'
"b:a" = '32k'
application = 'voip'
af = "highpass=f=200, lowpass=f=1000"


[presets.h264-realtime]
fileext = "mkv"
type = "v"
codec = "libx264"
preset = "faster"  # ultrafast superfast veryfast faster fast medium – default preset slow slower veryslow placebo

[presets.vp9-realtime]
pix_fmt='yuv420p' # TODO output defaults
fileext = "webm"
type = "v"
codec = "vp9"
speed=5
tile-columns=6
frame-parallel=1
threads=8
static-thresh=0
max-intra-rate=300
deadline="realtime"
crf=9
lag-in-frames=9
# TODO quality min max
row-mt=1
error-resilient=1


